#!/bin/sh
#
# This script should only be run after modifying any autoconf- or
# automake-related files (e.g. configure.ac or Makefile.am).  It is used to
# generate the configure script and Makefile.in files needed for compilation.
# If you're just trying to build and install OPSEC, use the regular
#   ./configure && make
# recipe.  This script is only for developers.

AUTORECONF=${AUTORECONF:-autoreconf}
ACLOCAL=${ACLOCAL:-aclocal}
AUTOCONF=${AUTOCONF:-autoconf}
AUTOHEADER=${AUTOHEADER:-autoheader}
AUTOMAKE=${AUTOMAKE:-automake}
LIBTOOLIZE=${LIBTOOLIZE:-libtoolize}

rm -rf autom4te.cache

if $AUTORECONF --version > /dev/null 2>&1 ; then
    echo "Using autoreconf"
    $AUTORECONF --verbose --install
else
    echo "Using manual bootstrap"
    $ACLOCAL -I m4
    $AUTOHEADER
    $LIBTOOLIZE --automake --install --copy
    $AUTOMAKE --add-missing --copy --no-force
    $AUTOCONF
fi

rm -f config.cache


# In case ltmain.sh is replaced...
# This is a hack to prevent libtool from stripping -fopenmp and -openmp from
# link commands when compiling with OpenMP support.  This libtool bug was fixed
# in the official source tree as of March 2011, so this hack won't be necessary
# in the future.
#sed -e 's:|-threads):|-threads|-fopenmp|-openmp):g' -i ltmain.sh || exit 1
